### ISSUE TITLE
Add `flavor` & `target` support for flutter_build

### ISSUE THREAD

**Issue by KevinGong2013** [dotdoom/fastlane-plugin-flutter#3]
Nice project.

please add `--flavor` & `--target` for `flutter build`

**Comment by dotdoom** [comment]
Thanks! Since I didn't really want to reinvent the parsing done by `flutter build` (build name and build number are special because they can be fetched automatically), I added a free-form set of arguments to `flutter_build` method.

Here's how you can use it:

```ruby
flutter_build(build: 'apk', build_args: ['--flavor', 'ab', '--target', 'lib/main2.dart'])
```

or if you prefer

```ruby
my_flavor = 'ab'
my_target = 'lib/main2.dart'
flutter_build(build: 'apk', build_args: %W(--flavor #{my_flavor} --target #{my_target}))
```

or for completely custom behavior

```ruby
flutter(args: %w(build apk --flavor ab --target lib/main2.dart))
```

Once the checks pass, this will be released in gem version 0.3.9.
